config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  devise_for :users, :controllers => {registrations: 'user/registrations', sessions: 'user/sessions'}

  get "/home", to: 'home#index'
  get "/dashboard", to: 'static_pages#dashboard'
  

  resources :posts

  resource :static_pages do
    member do
      get 'preview_stats'
      get 'preview_map'
      get 'preview_dashboard'
    end
  end
  match "dashboard/create_post(.:format)" => "static_pages#create_post", as: :create_post, via: :post
  match "user/update(.:format)" => "user#update_profile", as: :update_profile, via: :patch
  get "/user/account(.:format)" => "user#edit", as: :account
  get "/user/:id(.:format)" => 'user#profile', as: :user

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
	validates :comment, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :post_type, presence: true
	has_many :comments, dependent: :destroy
	belongs_to :user
	belongs_to :category
	geocoded_by :full_address
	after_validation :geocode

	enum post_type: { 
	  share_something: 0, 
	  need_help: 1}

	 
end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
		:recoverable, :rememberable, :trackable, :validatable

	# Validations
	validates :name, presence: true

	geocoded_by :full_address
	after_validation :geocode

	has_many :posts, dependent: :destroy
	has_many :comments, dependent: :destroy

	# Paperclip
	has_attached_file :avatar, :styles => { :thumb => "100x100>" },
		:default_url => "users/avatars/missing.png"
	validates_attachment_content_type :avatar, :content_type => /\Aimage/
	validates_attachment_file_name :avatar, :matches => [/png\Z/, /jpe?g\Z/]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  respond_to :html, :json

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
  end

  # Override error message from devise
  def errors_for(model, attribute)
    if model.errors[attribute].present?
      content_tag :span, :class => 'error_explanation' do
        model.errors[attribute].join(", ")
      end
    end
  end

  def after_sign_in_path_for(resource_or_scope)
    root_path
  end

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		if_user_redirect_to  
	end

	def if_user_redirect_to
		if current_user.present?
		  redirect_to dashboard_path
		end
	end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
end

app/controllers/post_controller.rb
class PostController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index
		@user = User.where(:id => current_user.id)
	end
	def dashboard
		@post = Post.new
		@user = User.where(:id => current_user.id)
		
	end

	def create_post
		@post = Post.new(post_params)
		@post.user_id = current_user.id
		respond_to do |format|
			if @post.save
				return render :json => {:success => true}
			else
				return render :json => {:success => false, :message=> @post.errors.join(", ")}
			end
		end
	end

	def preview_dashboard
		respond_to do | format |
			format.js {render :layout => false}
		end
	end

	def preview_map
		respond_to do | format |
			format.js {render :layout => false}
		end
	end

	def preview_map
		respond_to do | format |
			format.js {render :layout => false}
		end
	end

	def preview_stats
		@post_share = Post.joins(:category).group("categories.name").where(:post_type => 0).count
		@post_need = Post.joins(:category).group("categories.name").where(:post_type => 1).count
		respond_to do | format |
			format.js {render :layout => false}
		end
	end

	private

	def post_params
		params.require(:post).permit(:message, :full_address, :category_id, :status, :post_type, :phone)
	end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
  before_filter :configure_sign_in_params, only: [:create]

  def create
    resource = warden.authenticate!(:scope => resource_name, :recall => '#{controller_path}#failure')
    sign_in_and_redirect(resource_name, resource)
  end
  
  def sign_in_and_redirect(resource_or_scope, resource=nil)
    scope = Devise::Mapping.find_scope!(resource_or_scope)
    resource ||= resource_or_scope
    sign_in(scope, resource) unless warden.user(scope) == resource
    return render :json => {:success => true}
  end

  def failure
    return render :json => {:success => false, :errors => ["Login failed."]}
  end


  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  def configure_sign_in_params
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:email, :password) }
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	def profile
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def edit
		@user = User.find_or_initialize_by(id: current_user.id)
	end

	def update_profile
		@user = User.where(id: current_user.id)
		respond_to do |format|
			if @user.update(current_user.id, user_params)
				format.html { redirect_to root_path, notice: 'Profile was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: 'edit' }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end

	private
	def user_params
		params.require(:user).permit(:name, :full_address, :avatar, :about)
	end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis
	def full_title(page_title)
		base_title = "Charihub"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end

	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/helpers/user_helper.rb
module UserHelper
	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end
end

app/views/home/index.html.haml
%section#intro
  .container
    %nav.navbar{:role => "navigation"}
      .container-fluid
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          .navbar-brand{:href => "#"}
            %img{:height => "50", :src => image_path("logo-nav.png")}/
      / /.container-fluid
  %img{:alt => "logo", :src => image_path("logo-landing.png")}/
  %h1 
    Sharing across boundaries
  %p.lead
    Some people want to share, the others need helps.
    %br
    ChariHub connects them. 
  %button.btn.btn-warning.btn-lg{"data-target" => "#sign_up", "data-toggle" => "modal", :type => "button"} Join now
  %p.medium
    or
    %a{"data-target" => "#sign_in", "data-toggle" => "modal", :type => "button"} 
      Sign in

/ Modal
#sign_up.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "joinNow", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
          %span.sr-only Close
        %h4#myModalLabel.modal-title Join now!
      .modal-body
        = render 'user/registrations/new'

/ Modal
#sign_in.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "logIn", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
          %span.sr-only Close
        %h4#myModalLabel.modal-title Sign in
      .modal-body
        = render 'user/sessions/new'

%section#intro-feature.text-center
  .container
    %h1 Imagine we can help each other
    .row
      .col-md-4
        %img{:alt => "logo", :src => "holder.js/200x200"}/
        %h2 Place for sharing
        %p.lead Help can come from anywhere, but sometimes you don't know how to find it. Imagine where we can share our difficulties and find someone that can help us.
        %button.btn.btn-warning Learn more &raquo;
      .col-md-4
        %img{:alt => "logo", :src => "holder.js/200x200"}/
        %h2 Place for finding help
        %p.lead Help can come from anywhere, but sometimes you don't know how to find it. Imagine where we can share our difficulties and find someone that can help us.
        %button.btn.btn-warning Learn more &raquo;
      .col-md-4
        %img{:alt => "logo", :src => "holder.js/200x200"}/
        %h2 Know the world
        %p.lead Help can come from anywhere, but sometimes you don't know how to find it. Imagine where we can share our difficulties and find someone that can help us.
        %button.btn.btn-warning Learn more &raquo;

.container
  %hr

%section#share
  .container
    %h1.text-center
      %span.text-primary Share if you have more
      %small or
      %span.text-danger Ask for help.
    .row
      .col-md-6
        .panel.panel-primary
          .panel-body.lead
            I have extra 100kg of rice after big ceremony at my house. Anyone who know where I should grand this rice, please contact me.
          .panel-footer
            %a{:href => "#"} Annie
            shares her
            %span.label.label-primary Food
            on Saturday, December 6, 2014
        .panel.panel-primary
          .panel-body.lead
            I want to grand my bonus salary this year to charity. Where is the place that urgently need?
          .panel-footer
            %a{:href => "#"} Joey
            shares her
            %span.label.label-primary Money
            on Saturday, December 6, 2014
        .text-center
          %button.btn.btn-lg.btn-primary See all 39 donors
      / /col-md-6
      .col-md-6
        .panel.panel-danger
          .panel-body.lead
            My people in Desa Terpencil needs medicine.
          .panel-footer
            %a.text-danger{:href => "#"} Annie
            needs
            %span.label.label-danger Medicine
            on Saturday, December 6, 2014
        .panel.panel-danger
          .panel-body.lead
            Need help to renovate local orphanage.
          .panel-footer
            %a.text-danger{:href => "#"} Joey
            needs
            %span.label.label-danger Money
            on Saturday, December 6, 2014
        .text-center
          %button.btn.btn-lg.btn-danger See all 39 needs
      / /col-md-6

app/views/map/_map.html.haml
#map-container
  #map-canvas

app/views/static_pages/_default.html.haml
%h1.page-header Dashboard
.row.placeholders
  .col-xs-6.col-sm-3.placeholder
    %img.img-responsive{:alt => "Generic placeholder thumbnail", "data-src" => "holder.js/200x200/auto/sky"}
      %h4 Label
      %span.text-muted Something else
  .col-xs-6.col-sm-3.placeholder
    %img.img-responsive{:alt => "Generic placeholder thumbnail", "data-src" => "holder.js/200x200/auto/vine"}
      %h4 Label
      %span.text-muted Something else
  .col-xs-6.col-sm-3.placeholder
    %img.img-responsive{:alt => "Generic placeholder thumbnail", "data-src" => "holder.js/200x200/auto/sky"}
      %h4 Label
      %span.text-muted Something else
  .col-xs-6.col-sm-3.placeholder
    %img.img-responsive{:alt => "Generic placeholder thumbnail", "data-src" => "holder.js/200x200/auto/vine"}
      %h4 Label
      %span.text-muted Something else
%h2.sub-header Section title

app/views/static_pages/dashboard.html.haml
.container-fluid
  .row
    .col-sm-3.col-md-2.sidebar
      - 2.times do
        %br
      .well
        %table.table
          %thead
            %tr
              %th Hello, #{current_user.name} !
          %tbody
            %tr
              %td
                %span.fa.fa-home
                = link_to 'Dashboard', preview_dashboard_static_pages_path,  :remote => true
            %tr
              %td.fa.fa-newspaper-o
                = link_to 'Feed', '#' 
            %tr
              %td
                %span.fa.fa-map-marker
                = link_to 'Map', preview_map_static_pages_path,  :remote => true
            %tr
              %td
                %span.fa.fa-bar-chart
                = link_to 'Stats', preview_stats_static_pages_path,  :remote => true
            %tr
              %td
                %a{"data-target" => "#new_post", "data-toggle" => "modal", :type => "button"} 
                  %span.fa.fa-plus
                  New Post
          
      
    .col-sm-4.col-md-10
      #dashboard_preview
        = render 'default'
        
    .col-sm-9.col-sm-offset-3.col-md-10.col-md-offset-2.main
      


#new_post.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "logIn", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
          %span.sr-only Close
        %h4#myModalLabel.modal-title New Post
      .modal-body
        = render 'post/new'

app/views/static_pages/preview_dashboard.js.erb
$( "#dashboard_preview" ).html( "<%= escape_javascript( render "default" ) %>" );

app/views/static_pages/preview_map.js.erb
$( "#dashboard_preview" ).html( "<%= escape_javascript( render "map/map" ) %>" );
google.maps.event.addDomListener(window, 'load', initialize);
$(document).ajaxStop(initialize);

app/views/static_pages/preview_stats.js.erb
$( "#dashboard_preview" ).html( '<%= escape_javascript( render( :partial => "stats/stats", :locals => { :post_share => @post_share, :post_need => @post_need}) ) %>' );

app/views/stats/_stats.html.haml
= column_chart post_share, {library: {title: 'Someone share near you'}, colors: ["blue"]}
= column_chart post_need, {library: {title: 'Someone need help near you'}, colors: ["red"]}