config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  devise_for :users, :controllers => {registrations: 'user/registrations', sessions: 'user/sessions'}

  get "/home", to: 'home#index'
  get "/dashboard", to: 'static_pages#dashboard'
  

  resources :posts

  resource :static_pages do
    member do
      get 'preview_stats'
      get 'preview_map'
      get 'preview_dashboard'
    end
  end
  match "dashboard/create_post(.:format)" => "static_pages#create_post", as: :create_post, via: :post
  match "user/update(.:format)" => "user#update_profile", as: :update_profile, via: :patch
  get "/user/account(.:format)" => "user#edit", as: :account
  get "/user/:id(.:format)" => 'user#profile', as: :user

end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
		:recoverable, :rememberable, :trackable, :validatable

	# Validations
	validates :name, presence: true

	geocoded_by :full_address
	after_validation :geocode

	has_many :posts, dependent: :destroy
	has_many :comments, dependent: :destroy

	# Paperclip
	has_attached_file :avatar, :styles => { :thumb => "100x100>" },
		:default_url => "users/avatars/missing.png"
	validates_attachment_content_type :avatar, :content_type => /\Aimage/
	validates_attachment_file_name :avatar, :matches => [/png\Z/, /jpe?g\Z/]

end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_sign_up_params, only: [:create]
  # before_filter :configure_account_update_params, only: [:update]

  def create
    build_resource(sign_up_params)

    if resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_up(resource_name, resource)
        return render :json => {:success => true}
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        return render :json => {:success => true}
      end
    else
      clean_up_passwords resource
      return render :json => {:success => false, :message=> resource.errors.full_messages.join(", ")}
    end
  end

  def sign_up_params
    devise_parameter_sanitizer.sanitize(:sign_up)
  end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # You can put the params you want to permit in the empty array.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
  end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
  before_filter :configure_sign_in_params, only: [:create]

  def create
    resource = warden.authenticate!(:scope => resource_name, :recall => '#{controller_path}#failure')
    sign_in_and_redirect(resource_name, resource)
  end
  
  def sign_in_and_redirect(resource_or_scope, resource=nil)
    scope = Devise::Mapping.find_scope!(resource_or_scope)
    resource ||= resource_or_scope
    sign_in(scope, resource) unless warden.user(scope) == resource
    return render :json => {:success => true}
  end

  def failure
    return render :json => {:success => false, :errors => ["Login failed."]}
  end


  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  def configure_sign_in_params
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:email, :password) }
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	def profile
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def edit
		@user = User.find_or_initialize_by(id: current_user.id)
	end

	def update_profile
		@user = User.where(id: current_user.id)
		respond_to do |format|
			if @user.update(current_user.id, user_params)
				format.html { redirect_to root_path, notice: 'Profile was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: 'edit' }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end

	private
	def user_params
		params.require(:user).permit(:name, :full_address, :avatar, :about)
	end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/user_helper.rb
module UserHelper
	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end
end

app/views/user/edit.html.haml
- 2.times do
  %br
.row
  .col-md-6.col-md-offset-3
    .well
      = simple_form_for(@user, :url => update_profile_path, :method => :patch) do |f|
        = f.input :name, input_html: {value: @user.name}
        = f.input :full_address, placeholder: 'e.g 714 Green St, Big Town, MO'
        = f.input :about, placeholder: 'Tell me more about yourself :)', input_html: {value: @user.about}
        = f.input :avatar 
        = f.button :button, "Update".html_safe, data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Saving..."}
        

app/views/user/profile.html.haml
- 2.times do
  %br
.container
  .row
    .col-md-offset-2.col-md-8.col-lg-offset-3.col-lg-6
      .well.profile
        .col-sm-12
          .col-xs-12.col-sm-8
            %h2 #{@user.name}
            %p
              %strong Location:
              #{@user.full_address}
            %p
              %strong About:
              #{@user.about}
            %p
              %strong Categories:
              %span.tags Food
              %span.tags Money
  
          .col-xs-12.col-sm-4.text-center
            %figure
              %img.img-circle{:alt => "", :src => "http://" + @user.avatar.url(:thumb)}
              %figcaption.ratings
                %p
                  Ratings
                  %a{:href => "#"}
                    %span.fa.fa-star
                  %a{:href => "#"}
                    %span.fa.fa-star
                  %a{:href => "#"}
                    %span.fa.fa-star
                  %a{:href => "#"}
                    %span.fa.fa-star
                  %a{:href => "#"}
                    %span.fa.fa-star-o
        .col-xs-12.divider.text-center
          .col-xs-12.col-sm-4.emphasis
            %h2
              %strong 20
            %p
              %small Helps
            
          .col-xs-12.col-sm-4.emphasis
            %h2
              %strong 5
            %p
              %small Needs
            %button.btn.btn-success.btn-block
              %span.fa.fa-envelope
              Message
          .col-xs-12.col-sm-4.emphasis
            %h2
              %strong 15
            %p
              %small Helps accepted
            %button.btn.btn-danger{:type => "button"}
              %span.fa.fa-times
              Report this user
              
                